### ISSUE TITLE
Not working with Amarok 2.6 beta 1

### ISSUE THREAD

**Issue by krnekit** [alternativshik/vk_search#1]
When enable script, I see the following log in the terminal:

amarok: [ScriptsConfig] config changed 
amarok: BEGIN: void Amarok2ConfigDialog::updateButtons() 
amarok:   BEGIN: virtual bool Amarok2ConfigDialog::hasChanged() 
amarok:     BEGIN: virtual bool CollectionConfig::hasChanged() 
amarok:     END__: virtual bool CollectionConfig::hasChanged() [Took: 0s] 
amarok:     [ConfigDialog] Changed:  ScriptsConfig 
amarok:   END__: virtual bool Amarok2ConfigDialog::hasChanged() [Took: 0s] 
amarok: END__: void Amarok2ConfigDialog::updateButtons() [Took: 0s] 
amarok: BEGIN: void CollectionSetup::writeConfig() 
amarok: END__: void CollectionSetup::writeConfig() [Took: 0s] 
amarok: BEGIN: virtual void NotificationsConfig::updateSettings() 
amarok:   BEGIN: void App::applySettings(bool) 
amarok:     BEGIN: void Amarok::OSD::applySettings() 
amarok:     END__: void Amarok::OSD::applySettings() [Took: 0s] 
amarok:   END__: void App::applySettings(bool) [Took: 0.036s] 
amarok: END__: virtual void NotificationsConfig::updateSettings() [Took: 0.0 
amarok: BEGIN: virtual void PluginsConfig::updateSettings() 
amarok: END__: virtual void PluginsConfig::updateSettings() [Took: 0s] 
amarok: BEGIN: virtual void ScriptsConfig::updateSettings() 
amarok:   BEGIN: void Amarok2ConfigDialog::updateButtons() 
amarok:     BEGIN: virtual bool Amarok2ConfigDialog::hasChanged() 
amarok:       BEGIN: virtual bool CollectionConfig::hasChanged() 
amarok:       END__: virtual bool CollectionConfig::hasChanged() [Took: 0s] 
amarok:     END__: virtual bool Amarok2ConfigDialog::hasChanged() [Took: 0s] 
amarok:   END__: void Amarok2ConfigDialog::updateButtons() [Took: 0s] 
amarok:   BEGIN: void ScriptManager::configChanged(bool) 
amarok:     BEGIN: bool ScriptManager::slotRunScript(const QString&, bool) 
amarok:       BEGIN: void ScriptManager::startScriptEngine(const QString&) 
amarok:         [ScriptManager] start script engine: "vk_search" 
amarok:         BEGIN: ScriptableServiceScript::ScriptableServiceScript(QScripngine_) 
amarok:         END__: ScriptableServiceScript::ScriptableServiceScript(QScripngine_) [Took: 0s] 
amarok:       END__: void ScriptManager::startScriptEngine(const QString&) [To: 0s]  
amarok:       BEGIN: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) 
amarok:         importing qt bindings  "qt.core" 
amarok:       END__: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) [Took: 0.011s] 
amarok:       BEGIN: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) 
amarok:         importing qt bindings  "qt.gui" 
amarok:       END__: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) [Took: 0.029s] 
amarok:       BEGIN: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) 
amarok:         importing qt bindings  "qt.network" 
amarok:       END__: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) [Took: 0.003s] 
amarok:       BEGIN: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) 
amarok:         importing qt bindings  "qt.uitools" 
amarok:       END__: bool AmarokScript::ScriptImporter::loadQtBinding(const QSing&) [Took: 0s] 
"QFormBuilder was unable to create a custom widget of the class 'QWebView'; deulting to base class 'QWidget'." 
amarok:       [ERROR__] [ScriptManager] "Script Error: TypeError: Result of exession 'webView.urlChanged' [undefined] is not an object. (line: 43)" 
amarok:       BEGIN: void ScriptManager::slotStopScript(const QString&) 
amarok:         no such service to remove 
amarok:         [ScriptManager] Disabling sccript "vk_search" 
amarok(13984)/kdecore (KPluginInfo) KPluginInfo::save: no KConfigGroup, cannotave 
amarok:         BEGIN: void ScriptManager::scriptFinished(const QString&) 
amarok:           BEGIN: virtual ScriptableServiceScript::~ScriptableServiceScpt() 
amarok:           END__: virtual ScriptableServiceScript::~ScriptableServiceScpt() [Took: 0s] 
amarok:         END__: void ScriptManager::scriptFinished(const QString&) [Too 0.008s]  
amarok:       END__: void ScriptManager::slotStopScript(const QString&) [Took:.009s]  
amarok:       [ScriptManager] The Log For the script that is the borked:  ("152:57 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "15:32:57 Script ended", "15:33:25 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "15:33:25 Script ended", "15:34:14 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "15:34:14 Script ended", "15:34:43 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "15:34:43 Script ended", "15:35:00 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "15:35:00 Script ended", "16:08:49 Script started", "Script Error: TypeError: Result of expression 'webView.urlChanged' [undefined] is not an object. (line: 43)", "16:08:49 Script ended") 
amarok:     END__: bool ScriptManager::slotRunScript(const QString&, bool) [Took: 0.06s] 
amarok:   END__: void ScriptManager::configChanged(bool) [Took: 0.06s] 
amarok: END__: virtual void ScriptsConfig::updateSettings() [Took: 0.063s] 
amarok: BEGIN: virtual bool Amarok2ConfigDialog::hasChanged() 
amarok:   BEGIN: virtual bool CollectionConfig::hasChanged() 
amarok:   END__: virtual bool CollectionConfig::hasChanged() [Took: 0s] 
amarok: END__: virtual bool Amarok2ConfigDialog::hasChanged() [Took: 0s]

**Comment by krnekit** [comment]
Может не стоит пока закрывать, не исправлено же еще?

**Comment by alternativshik** [comment]
именно это решено - надо установить  libqtwebkit-dev

**Comment by krnekit** [comment]
Зачем скрипту нужен devel пакет? Там же заголовочники для линковки.
И тем не менее, пакет установлен, но скрипт не работает - значит проблема не в этом.
libqtwebkit2.2-devel, версия 2.2.1

**Comment by alternativshik** [comment]
я не знаю, зачем, но при тестах установка именно этого пакета решала
указанную проблему именно с этой ошибкой. Какой дистр и версии всех пакетов
- кде, амарок и тд?

4 июня 2012 г., 22:12 пользователь krnekit <
reply@reply.github.com

> написал:
> 
> Зачем скрипту нужен devel пакет? Там же заголовочники для линковки.
> И тем не менее, пакет установлен, но скрипт не работает - значит проблема
> не в этом.
> libqtwebkit2.2-devel, версия 2.2.1
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alternativshik/vk_search/issues/1#issuecomment-6107617

## 

Best regards, Sergey Maltsev

**Comment by krnekit** [comment]
Это очень странно, ибо в том пакете не должно быть ничего, что используется скриптом. разве что по зависимостям вытащился qtwebkit, но он у меня тоже установлен.

Дистр Mageia 2, i586. KDE 4.8.2, Qt 4.8.1.
Amarok 2.6 beta 1, собранный из исходников, все возможные модули включены.

**Comment by krnekit** [comment]
Возможно версия qtwebkit не подходит?

**Comment by alternativshik** [comment]
ЗАчем дев. пакет я сам не понял, но данная проблема была воспроизведена на чистой системе и починилась установкой именно этого пакета с зависимостями. Это сработало в убунте.

**Comment by krnekit** [comment]
Нашел, в чем была проблема. Не был установлен плагин для QtDesigner, позволяющий использовать в нем компоненты QtWebKit (конкретно QWebView). В скрипте используется ui-файл и, видимо, для его отображения применяются те же механизмы, что использует дизайнер для предпросмотра и т.п.
Я недавно обновлял систему и этого плагина не оказалось, хотя раньше он был. Поиск выдает несколько похожих проблем для разных систем, где с переходом на Qt 4.8 этот плагин пропал, я так понял, там что-то поменялось в сборке и надо было адаптировать спеки.
В общем, если что, у меня в системе это пакет называется qt4-designer-plugin-webkit.
