### ISSUE TITLE
Амперсанд в названии песни отображается в списке как '&amp;'

### ISSUE THREAD

**Issue by krnekit** [alternativshik/vk_search#3]
Скриншот: http://i25.fastpic.ru/big/2012/0612/50/89e13bcf15f7922491f31f75d55e8d50.png

**Comment by alternativshik** [comment]
Ага, спасибо. Исправлю.

2012/6/12 krnekit <
reply@reply.github.com

> Скриншот:
> http://i25.fastpic.ru/big/2012/0612/50/89e13bcf15f7922491f31f75d55e8d50.png
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/alternativshik/vk_search/issues/3

## 

Best regards, Sergey Maltsev

**Comment by alternativshik** [comment]
fix
