### ISSUE TITLE
Статус undefined при проигрывании файла из локальной коллекции

### ISSUE THREAD

**Issue by krnekit** [alternativshik/vk_search#4]
Проигрывание файла из локальной коллекции устанавливает ВКонтакте статус undefined.

**Comment by alternativshik** [comment]
Угу, пофиксим.

**Comment by krnekit** [comment]
Точнее даже если стату пустой и
- проигрывается файл из локальной коллекции
- файл из вконтакта, но не включена опция транслировать проигрываемую музыку в статус.

При этом скрипт берет последни статус и устанавливает его принудительно, даже если он был убран уже. Если до этого был пустой статус - то ставит undefined.
